AUDIORECEIVER_VERSION = 5da3a3789ebfd26f651ad1ec16317d507cfbf4b7
AUDIORECEIVER_SITE = $(call github,34vdf34,audioreceiver,$(AUDIORECEIVER_VERSION))
AUDIORECEIVER_DEPENDENCIES = gstreamer1 gst1-plugins-base
AUDIORECEIVER_PREFIX = $(TARGET_DIR)/usr
AUDIORECEIVER_LICENSE = gplv2

define AUDIORECEIVER_BUILD_CMDS
     $(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D)
endef


define AUDIORECEIVER_INSTALL_TARGET_CMDS
        (cd $(@D); cp audioreceiver $(AUDIORECEIVER_PREFIX)/bin)
endef

define AUDIORECEIVER_CLEAN_CMDS
        $(MAKE) $(AUDIORECEIVER_MAKE_OPTS) -C $(@D) clean
endef

$(eval $(generic-package))
